routes/web.php
<?php


Route::get('/', function () {
    return view('inicio');
});

 Route::resource('/portafolio', 'Publicacion\ControllerPublicacion@general');

 Route::resource('/index', 'Index\IndexController');
  Route::resource('/aportes', 'Aprotes\AportesController@aportes');
 Route::resource('/estudios', 'Index\IndexController@estudios');
 Route::resource('/informacion', 'Index\IndexController@informacion');

 

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'Administrador'], function () {

    Route::resource('Ciudad', 'Ciudad\CiudadController');

    Route::resource('Informacion', 'Informacion\InformacionController');

    Route::resource('Categoria', 'Categoria\categoriaController');

    Route::resource('Portafolio', 'Portafolio\PortafioController');

    Route::resource('Secciones', 'Secciones\ControllerSecciones');

    Route::resource('Publicaciones', 'Publicacion\ControllerPublicacion');

    Route::resource('Estudios', 'Estudios\EstudiosController');

    Route::resource('Aportes', 'Aprotes\AportesController');

});

app/Models/Ciudad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ciudad extends Model
{
    protected $table    = "ciudad";
    protected $fillable = ['nombre'];
    protected $guarded  = ["id"];
    public $timestamps  = false;
}

app/Http/Controllers/Ciudad/CiudadController.php
<?php

namespace App\Http\Controllers\Ciudad;

use App\Http\Controllers\Controller;
use App\Models\Ciudad;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
class CiudadController extends Controller
{
    public function index()
    {
        $ciudad = Ciudad::all();

        return view('ciudad.ciudad')->with('ciudad', $ciudad);
    }

    public function store(Request $request)
    {
        $ciudad = new Ciudad($request->all()); //almaceno todos los datos recibidos de la vista dentro de la variable  $backlog
        $ciudad->save(); //guardo todo lo que contenga la variable backlog

        $ciudad = Ciudad::all();
        Flash::success('se registro la informacion');

        return view('ciudad.ciudad')->with('ciudad', $ciudad);
    }

    public function edit($id)
    {
        $ciudad = Ciudad::find($id);

        return view('ciudad.editar')->with('ciudad', $ciudad);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $ciudad = Ciudad::find($id); //busco el backlog que provenga de la vista mediante el $id que solicito en el formulario de la vista
        $ciudad->fill($request->all()); //almaceno todos los datos recibidos de la vista dentro de la variable  $backlogs
        $ciudad->save(); //guardo todo lo que contenga la variable $backlogs

        $ciudad = Ciudad::all();
        return view('ciudad.ciudad')->with('ciudad', $ciudad);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ciudad/ciudad.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        
                <div class="panel-heading">
                <div class="container">
                    <div class="container">
                    
<h2>Ciudad</h2>
</div>  
                </div>    
                </div>

                <div class="panel-body">
                    <div class="container-fluid">
                        <div class="card">
                <div class="card-header d-flex align-items-center">
                  
                </div>
                <div class="card-block">
                            <div class="panel-body">
                                @if(count($errors) >0)
                                    <div class="alert alert-danger" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{$error}}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                  @include('flash::message')

                                <div class="table-responsive">
                                   <table class="table table-hover table-sm table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>Identificador</th>
                                            <th>Nombre</th>
                                            <th>acciones</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($ciudad as $ciudad)
                                        <tr>
                                                <td >{{ $ciudad -> id }}</td>
                                                <td>{{ $ciudad -> nombre}}</td>
                                                <td>
                                                <center>
                                                    <a  class="btn btn-success" href="{{route('Ciudad.edit', $ciudad->id)}}">
                                                        Editar
                                                    </a>
                                                </center>
                                            </td>
                                        </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    <a >

                                        <button type="button" class="btn btn-success" data-toggle="modal"   data-target="#Crear">Nueva <i class="fa fa-fw fa-plus"></i></button></a><br><br>
                                </div>
                            </div>
                    </div>
                </div>

                       
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="Crear" class="modal fade" role="dialog">
                                <div class="modal-dialog">

                                        <!-- Modal content-->
                                    <div class="modal-content">
                                          <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Registro de Peticion</h4>
                                          </div>
                                          <div class="modal-body">


                                        {!! Form::open(['route' => 'Ciudad.store', 'method' => 'POST']) !!}

                                        <div class="form-group">
                                            {!! Form::label('name', 'Nombre') !!}
                                            {!! Form::text('nombre', null, ['class' =>'form-control', 'requerid', 'placeholder' => 'Nombre de la peticion']) !!}
                                        </div>
                                        <div class="modal-footer">
                                            {!! Form::submit('Registrar', ['class' =>'btn btn-success col-md-offset-5']) !!}
                                        </div>

                                        {!! Form::close() !!}
                                        </div>

                                    </div>
                                </div>
                            </div>
@endsection

resources/views/ciudad/editar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    {!! Form::open(['route' => ['Ciudad.update',$ciudad->id], 'method' => 'PUT']) !!}

                                        <div class="form-group">
                                            {!! Form::label('name', 'Nombre') !!}
                                            {!! Form::text('nombre', $ciudad->nombre, ['class' =>'form-control', 'requerid', 'placeholder' => 'Nombre de la peticion']) !!}
                                        </div>
                                        <div class="modal-footer">
                                            {!! Form::submit('Registrar', ['class' =>'btn btn-success col-md-offset-5']) !!}
                                        </div>

                                        {!! Form::close() !!}
                                    </div>


@endsection